#!/bin/bash

# Emma's GitHub Repository Creator for Gymate Project
# 使用帳戶: emmaclaw2026@gmail.com

echo "🚀 Gymate GitHub 倉庫創建指南"
echo "============================"
echo "⏰ 準備時間: $(date '+%Y-%m-%d %H:%M:%S HKT')"
echo "📁 專案名稱: gymate"
echo "👤 GitHub帳戶: emmaclaw2026@gmail.com"
echo ""

echo "📋 創建步驟"
echo "----------"

echo "步驟 1: 安裝 GitHub CLI"
echo "----------------------"
echo "在終端機中執行以下命令："
echo "curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
echo "sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg"
echo "echo 'deb [arch=\$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main' | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null"
echo "sudo apt update"
echo "sudo apt install gh"
echo ""

echo "步驟 2: 登錄 GitHub 帳戶"
echo "------------------------"
echo "安裝完成後，執行："
echo "gh auth login"
echo "選擇："
echo "- Account: emmaclaw2026@gmail.com"
echo "- Git protocol: HTTPS"
echo "- 登錄方式: 瀏覽器登錄"
echo ""

echo "步驟 3: 創建遠端倉庫"
echo "------------------"
echo "在 gymate 專案目錄中執行："
echo "cd /path/to/gymate"
echo "gh repo create gymate --public --description 'Gym and fitness management system' --source=. --remote=origin --push"
echo ""

echo "步驟 4: 初始化本地 Git 倉庫"
echo "--------------------------"
echo "執行以下命令："
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit: Gymate project structure'"
echo "git branch -M main"
echo ""

echo "步驟 5: 推送到 GitHub"
echo "---------------------"
echo "git remote add origin https://github.com/emmaclaw2026/gymate.git"
echo "git push -u origin main"
echo ""

echo "🔧 項目配置"
echo "----------"
echo "創建完成後，建議添加以下文件："
echo "- .gitignore (忽略 Python 和 IDE 文件)"
echo "- LICENSE (MIT 授權)"
echo "- CONTRIBUTING.md (貢獻指南)"
echo "- .env.example (環境變數範例)"
echo ""

echo "🎯 預期結果"
echo "----------"
echo "✅ GitHub 倉庫: https://github.com/emmaclaw2026/gymate"
echo "✅ 專案代碼已上傳"
echo "✅ 完整的專案說明"
echo "✅ 可被其他人訪問和 Fork"
echo ""

echo "💡 注意事項"
echo "----------"
echo "1. 確保 GitHub 帳戶已登錄"
echo "2. 確保有網路連接"
echo "3. 確認沒有權限問題"
echo "4. 檢查 README.md 內容是否正確"
echo ""

echo "🚀 執行建議"
echo "----------"
echo "您可以："
echo "1. 手動按照上述步驟操作"
echo "2. 或者提供 sudo 權限讓我自動執行"
echo "3. 或者我為您準備完整的壓縮包讓您上傳"
echo ""

echo "✅ 創建準備就緒！"
echo "📞 需要協助請告訴我！"